"""html compositions / slug

Revision ID: f45ccd692414
Revises: 
Create Date: 2022-11-29 20:05:50.930529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45ccd692414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositions', sa.Column('description_html', sa.Text(), nullable=True))
    op.add_column('compositions', sa.Column('slug', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'compositions', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compositions', type_='unique')
    op.drop_column('compositions', 'slug')
    op.drop_column('compositions', 'description_html')
    # ### end Alembic commands ###
